### PR TITLE
Add echarts example

### PR DESCRIPTION
**Pull request by ScottHuangZL**
echarts is famous chart lib create by Baidu.  And donate to Apache recently. It is very popular and powerful.
https://echarts.apache.org/en/tutorial.html#Get%20Started%20with%20ECharts%20in%205%20minutes

**Add echarts example for flexx**

### CODE REVIEW

**Comment by almarklein** [comment]
Thanks, this is a great addition!

**Comment by ScottHuangZL** [comment]
Thanks for recognize this addition:)  This example can teach people how to warp a JS library into FlexxUI easily.

Can you add this widget example into your https://flexx.readthedocs.io/en/stable/examples/index.html#howtos ? Thanks.

And thanks for provide great FlexxUI, it is a good software!   I am new at Python, but can quickly ramp up according your documentation, thanks for your support.

**Comment by almarklein** [comment]
It's here: https://flexx.readthedocs.io/en/latest/examples/index.html#howtos

(it wasn't yet, for some reason I had to manually trigger a build). It will automatically appear in `latest` when a new release is made.

**Comment by ScottHuangZL** [comment]
Thank you @almarklein .

**Pull request merged**
