### PR TITLE
add psutil requirement

### PR DESCRIPTION
**Pull request by maphew**
btw, it's no longer necessary to convert markdown to rst for pypi :-)

### CODE REVIEW

**Comment by Korijn** [comment]
If this is only required for the CPU monitoring demo, I would advise against adding it to the package requirements. Is it used for other purposes?

**Comment by almarklein** [comment]
I agree with @Korijn here. The only use-case is in that (and maybe another) demo.

**Comment by almarklein** [comment]
That said, I appreciate the contribution and don't want to discourage you, @maphew !

**Comment by almarklein** [comment]
Ok, I just read #525 and see the confusion. The correct way to fix this would be to wrap the `import psutil` in a `try-except` and reraise the error with a clear message that one should install `psutil`.

**Comment by maphew** [comment]
No discouragement felt! I was dithering about it being a good idea. In the end I came down on the side of "examples in the docs should just work", but I've no firm opinion about it.

**Pull request closed without merging**
