### PR TITLE
Improve docs on Widget.keypres event

### PR DESCRIPTION
**Pull request by almarklein**
It seems that the gist of it to always use keydown, unless I miss something.

### CODE REVIEW

**Comment by Korijn** [comment]
keypress is useful when you only want to receive events for keys that actually input a character. it avoids the need to filter oit events for e.g. shift or delete key events.

that's all I can think of.

**Comment by almarklein** [comment]
Yeah, that was what I thought. Unfortunately, Firefox passes arrow keys/backspace/more? and Chrome does not. Well, that's the web :D

**Comment by Korijn** [comment]
Indeed it is.

**Comment by almarklein** [comment]
I guess Firefox' reasoning is to only suppress modifier keys, because these are typically held down, which would cause them to fire in fast succession.

**Pull request merged**
